#!/bin/bash

RUNTECPLOT=/home/spfeife/PACKAGES/tecplot/bin/tec360

# list of variable for tecplot-macro
varnamel=" '\"x\" \"mu\"  '" 


echo "1: $1 "

FILENAME=$1


function make_mcr {
echo "#!MC 1200" > temp.mcr
echo "# Created by Tecplot 360 build 12.2.0.9077" >> temp.mcr
echo "\$!READDATASET  '$FILENAME' " >> temp.mcr
echo "  READDATAOPTION = NEW" >> temp.mcr
echo "  RESETSTYLE = YES" >> temp.mcr
echo "  INCLUDETEXT = NO" >> temp.mcr
echo "  INCLUDEGEOM = NO" >> temp.mcr
echo "  INCLUDECUSTOMLABELS = NO" >> temp.mcr
echo "  VARLOADMODE = BYNAME" >> temp.mcr
echo "  ASSIGNSTRANDIDS = YES" >> temp.mcr
echo "  INITIALPLOTTYPE = XYLINE" >> temp.mcr
echo "  VARNAMELIST = $varnamel" >> temp.mcr
echo "\$!XYLINEAXIS YDETAIL 1 {RANGEMIN = -0.04}" >> temp.mcr
echo "\$!XYLINEAXIS YDETAIL 1 {RANGEMAX = 0.04}" >> temp.mcr
echo "\$!XYLINEAXIS AUTOADJUSTRANGESTONICEVALUES = YES" >> temp.mcr
echo "\$!EXPORTSETUP EXPORTFORMAT = JPEG" >> temp.mcr
echo "\$!EXPORTSETUP IMAGEWIDTH = 817" >> temp.mcr
echo "\$!EXPORTSETUP  QUALITY = 100" >> temp.mcr
echo "\$!EXPORTSETUP EXPORTFNAME = '$FILENAME.jpg'" >> temp.mcr
echo "\$!EXPORT " >> temp.mcr
echo "  EXPORTREGION = CURRENTFRAME" >> temp.mcr
echo "\$!QUIT" >> temp.mcr
}

# execute tecplot only if jpg-file does not exist
if [ ! -e $FILENAME.jpg ]; then  

	make_mcr $FILENAME
	$RUNTECPLOT -b temp.mcr
	#convert -crop 613x103+106+543 $FILENAME.jpg crop_$FILENAME.jpg
	mv $FILENAME.jpg mu.jpg/$FILENAME.jpg
	#rm $FILENAME.jpg
	rm -f temp.*
	rm batch.log


fi 

